language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install nosetests
# command to run tests
script:
  - nosetests --with-coverage

# push report to coveralls.io
after_success:
- coveralls