language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install nose
# command to run tests
script:
  - pytest api/test_api.py 

# push report to coveralls.io
after_success:
- coveralls