language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls
# command to run tests
before_script:
 - psql -c 'create database maintenance_tracker;' -U postgres

script:
  - nosetests --with-coverage

# push report to coveralls.io
after_success:
- coveralls